<a href="https://colab.research.google.com/github/bondiolandia/TP_Laboratorio_de_M-todos_Cuantitativos_2026/blob/main/notebook_Evolucion_del_Anime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Holas Chicas!!
Para commitear un cambio, una vez que escriben el codigo, van a Archivo > Guardar. Una vez guardado van Archivo > Guardar una copia en Github; agregan un comentario que describa los cambios que estan pusheando y le dan OK.

In [2]:
%pip install -q pandas numpy matplotlib seaborn

In [3]:
import pandas as pd
import matplotlib as mp
import seaborn as sb
import numpy as np


Hacemos una primera exploración de los datos que tenemos.

In [6]:
# Importamos la libreria de Kaggle y el data set con el que vamos a trabajar
import kagglehub as kg
from kagglehub import KaggleDatasetAdapter

camino = "anime-dataset-2026.csv"
Datos = kg.dataset_load(KaggleDatasetAdapter.PANDAS,"darkbarrierhub/anime-dataset-2026",camino)

# Seleccionamos una porcion de los datos para explorar
muestra = pd.concat([Datos.head(),Datos.tail()])
display(muestra)

# Describimos la estructura de la tabla: dimensiones, columnas, tipos de dato (.dtypes).
filas, columnas = Datos.shape

print(f"El DF orginal tiene {filas} y {columnas} columnas\n")
Datos.info()

Using Colab cache for faster access to the 'anime-dataset-2026' dataset.

,anime_id,Name,English name,Other name,Score,Genres,Synopsis,Type,Episodes,Aired,...,Studios,Source,Duration,Rating,Rank,Popularity,Favorites,Scored By,Members,Image URL
0,1,Cowboy Bebop,Cowboy Bebop,カウボーイビバップ,8.75,"Action, Award Winning, Sci-Fi, Adult Cast, Space","Crime is timeless. By the year 2071, humanity ...",TV,26,"Apr 3, 1998 to Apr 24, 1999",...,Sunrise,Original,24 min. per ep.,R - 17+ (violence & profanity),50,41,90976,1077271,2089081,https://cdn.myanimelist.net/images/anime/4/196...
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,カウボーイビバップ 天国の扉,8.38,"Action, Sci-Fi, Adult Cast, Space","Another day, another bounty—such is the life o...",Movie,1,"Sep 1, 2001",...,Bones,Original,1 hr. 55 min.,R - 17+ (violence & profanity),252,663,1827,234731,417292,https://cdn.myanimelist.net/images/anime/1439/...
2,6,Trigun,Trigun,トライガン,8.22,"Action, Adventure, Sci-Fi, Adult Cast, Shounen","Vash the Stampede is the man with a $$60,000,0...",TV,26,"Apr 1, 1998 to Sep 30, 1998",...,Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older,433,268,17956,405835,846067,https://cdn.myanimelist.net/images/anime/1130/...
3,7,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),7.24,"Action, Drama, Mystery, Supernatural, Detective","Though hidden away from the general public, Wi...",TV,26,"Jul 3, 2002 to Dec 25, 2002",...,Sunrise,Original,25 min. per ep.,PG-13 - Teens 13 or older,3558,2003,720,46691,132072,https://cdn.myanimelist.net/images/anime/10/19...
4,8,Bouken Ou Beet,Beet the Vandel Buster,冒険王ビィト,6.97,"Action, Adventure, Fantasy, Shounen",It is the dark century and the people are suff...,TV,52,"Sep 30, 2004 to Sep 29, 2005",...,Toei Animation,Manga,23 min. per ep.,PG - Children,5016,6031,18,6983,16793,https://cdn.myanimelist.net/images/anime/7/215...
30758,65097,AIYOU,AIYOU,AIYOU,UNKNOWN,Music,Music video for the song AIYOU by Eve. The son...,Music,1,"Oct 2, 2026",...,UNKNOWN,Original,2 min.,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1900/...
30759,65098,22 Durnham Dew,UNKNOWN,22 Durnham Dew,UNKNOWN,"Slice of Life, Music",Music video for the song 22 Durnham Dew by Ben...,Music,1,"Jul 28, 2026",...,UNKNOWN,Original,1 min.,G - All Ages,UNKNOWN,30608,0,UNKNOWN,16,https://cdn.myanimelist.net/images/anime/1045/...
30760,65099,"Ghost (Music, 2026)",UNKNOWN,GHOST,UNKNOWN,"Sci-Fi, Music, Racing","Music video for the song Ghost by lIlBOI, BIG ...",Music,1,"Oct 2, 2026",...,UNKNOWN,Original,3 min.,PG-13 - Teens 13 or older,UNKNOWN,30605,0,UNKNOWN,21,https://cdn.myanimelist.net/images/anime/1833/...
30761,65100,Angels on the Dancefloor,UNKNOWN,Angels On The Dancefloor,UNKNOWN,"Music, Video Game",Music video for the song Angels On The Dancefl...,Music,1,"May 29, 2026",...,Mimoid,Original,4 min.,PG-13 - Teens 13 or older,UNKNOWN,30607,0,UNKNOWN,18,https://cdn.myanimelist.net/images/anime/1845/...
30762,65101,Goemul,Monster,괴물,UNKNOWN,Music,Music video for the song Goemul by WE GO-6.,Music,1,"Sep 22, 2026",...,UNKNOWN,Original,3 min.,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1239/...

El DF orginal tiene 30763 y 24 columnas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30763 entries, 0 to 30762
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   anime_id      30763 non-null  int64
 1   Name          30763 non-null  object
 2   English name  30763 non-null  object
 3   Other name    30763 non-null  object
 4   Score         30763 non-null  object
 5   Genres        30763 non-null  object
 6   Synopsis      30763 non-null  object
 7   Type          30763 non-null  object
 8   Episodes      30763 non-null  object
 9   Aired         30763 non-null  object
 10  Premiered     30763 non-null  object
 11  Status        30763 non-null  object
 12  Producers     30763 non-null  object
 13  Licensors     30763 non-null  object
 14  Studios       30763 non-null  object
 15  Source        30763 non-null  object
 16  Duration      30763 non-null  object
 17  Rating        30182 non-null  object
 18  Rank          30763 non-null  object
 19  Popularity    30763 non-null  int64
 20  Favorites     30763 non-null  int64
 21  Scored By     30763 non-null  object
 22  Members       30763 non-null  int64
 23  Image URL     30763 non-null  object
dtypes: int64(4), object(20)
memory usage: 5.6+ MB

Para analizar de forma rapida la cobertura temporal usamos el siguiente prompt:


```
# La columna de "airing" me serviria para saber que cobertura temporal tiene la tabla. Escribi unas lineas de codigo (py) para normalizarla de forma sencilla usando esta logica: extrae todas las fechas numericas (solo YYYY) que figuran en la columna airing, arma un array con ellas y busca min y max. El objetivo es poder normalizar el formato de fecha para extraer cual es la fecha mas antigua y cual la mas reciente, para inferir la cobertura temporal de los datos
```

In [ ]:

## Extraer todos los años (4 dígitos) de cada fila de "Aired"
anios_por_fila = Datos["Aired"].astype(str).str.findall(r"\b(\d{4})\b")

## Aplanar en un único array de enteros
anios = pd.Series([int(a) for lista in anios_por_fila for a in lista])

## Finalmente vemos la cobertura
print("Años extraídos:", len(anios))
print("Año más antiguo:", anios.min())
print("Año más reciente:", anios.max(), "(Puede contener futuros estrenos)")
print(f"Filas sin ningún año: {(anios_por_fila.str.len() == 0).sum()} de {len(Datos)}")

Miramos ahora la calidad de los datos y algunas medidas descriptivas

In [5]:
# Analizamos la calidad: valores nulos, duplicados y estadísticas descriptivas
filas = []

for col in Datos.columns:
    n_nulos = Datos[col].isnull().sum()
    if n_nulos > 0:  # solo columnas con nulos
        filas.append({
            "columna": col,
            "filas_nulas": n_nulos
        })

resumen_nulos = pd.DataFrame(filas).sort_values("filas_nulas", ascending=False).reset_index(drop=True)
display (resumen_nulos)
print (f"Cantidad de filas duplicadas: {Datos.duplicated().sum()}")

Datos.describe().T

  columna  filas_nulas
0  Rating          581

Cantidad de filas duplicadas: 0

,count,mean,std,min,25%,50%,75%,max
anime_id,30763.0,35685.588597,20237.227396,1.0,17684.0,39329.0,53047.5,65101.0
Popularity,30763.0,15227.872867,8880.868068,0.0,7535.5,15227.0,22918.0,30608.0
Favorites,30763.0,429.174528,4582.160441,0.0,0.0,1.0,17.0,256516.0
Members,30763.0,39192.862465,170966.328008,0.0,241.0,1051.0,9162.0,4434071.0

# **Conclusiones**
* La lectura del .info() nos dice dos cosas importantes: una porque es mentira y otra porque afecta todo el trabajo. La mentira: No existen columnas sin datos (no existen columnas con null). La anticipatoria: Columnas que podrian ser numericas son de tipo string.
* El Sondeo de cobertura temporal que hicimos es util pero preliminar: Es posible que el año mas reciente sea una fecha futura, pues el anime tiene una fecha posible de estreno. Por otro lado, nos dice "En que franja temporal se empezaron a emitir los animes que se incluye en la base", no cual es el momento en el que se hizo el relevamiento.
* Si nos dejasemos llevar solo por el isnull(), pensariamos que solo faltan datos en la columna Rating. Pero viendo la muestra vemos que hay celdas con valores como `"UNKNOWN", "Unknown", "Not available", "N/A"` y `"?"`. Vamos a tener que tener cuidado con estos: convertirlos a NaN o borrarlos segun lo que querramos mirar.
* No vemos filas duplicadas en su totalidad, pero si tenemos que saber que a veces se registra una serie en mas de una fila porque tiene peliculas, varias temporadas, remakes, etc.
*   Las estadisticas descriptivas de Pandas no nos sirven por el tipo de datos que tiene la base: Muchos que son conceptualmente numericos y podriamos evaluar su promedio (Numero de episodios, miembros de la pagina que lo agregaron a sus listas, ranking) no tienen un formato numerico si no que son del tipo Object. A estos tendremos que transformarlos para poder trabajarlos


**En resumen, tendremos que pensar alguna forma de sanear ciertas columnas para que nos sirvan (ej. fechas) y desechar algunas que no hacen a nuestra dimension de analisis (rating).**

In [ ]:
import pandas as pd

# Leer el archivo CSV descomprimido
anime = pd.read_csv("/content/anime-dataset-2026.csv")
print(anime.info())
anime.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/anime-dataset-2026.csv'

#**¿Qué factores influyen en que un anime sea más popular que otro?**

Aunque en su país de origen, la palabra anime se refiere a todo tipo de animacion de todo el mundo, fuera de este, el término "anime", es un término con el que se identifica a la animacion de procedencia japonesa.

Este genero de animacion tiene una considerable cantidad de fans no solo en su país de origen, sino en todas partes del mundo, prueba de esto es que el mercado mundial de anime alcanzó un valor de 46.540 millones de dólares en 2026 y se espera que incremente a 96.970 millones de dólares en 2034.

Por lo que, no solo como fanes, sino como clientas activas del anime, queremos ver la popularidad de los animes de forma mas analítica.

Myanimelist: La mayor base de datos y red social de anime, la cual contiene miles de fichas oficiales de animes que cualquiera puede ver, permitiendole a sus usuarios calificarlos a su antojo.

Dicho esto, desde el punto de vista de que los animes mas aclamados por los espectadores fueron uno de los principales aspectos que hicieron este incremento tan exponencial de la visualizacion de anime, hemos encontrado un Dataset publico en kaggle, que extrajo desde Myanimelist informacion de mas de 30.000 animes y sus calificaciones, de modo que, nos encargaremos de analizarlo para hallar cuales son los factores que influyeron en las mejores calificaciones.

In [ ]:
import kagglehub as kg
from kagglehub import KaggleDatasetAdapter
import pandas as pd

camino = "anime-dataset-2026.csv"
Datos = kg.dataset_load(KaggleDatasetAdapter.PANDAS,"darkbarrierhub/anime-dataset-2026",camino)

Using Colab cache for faster access to the 'anime-dataset-2026' dataset.

In [ ]:
Datos["Score"] = pd.to_numeric(Datos["Score"], errors='coerce')
Animes_Bien_Valorados = Datos[Datos["Score"].between(7, 10)]
print(f"La cantidad de animes con una calificacion superior a 7 son {Animes_Bien_Valorados['Score'].count()}")

La cantidad de animes con una calificacion superior a 7 son 5335

In [ ]:

Animes_Bien_Valorados.head()

,anime_id,Name,English name,Other name,Score,Genres,Synopsis,Type,Episodes,Aired,...,Studios,Source,Duration,Rating,Rank,Popularity,Favorites,Scored By,Members,Image URL
0,1,Cowboy Bebop,Cowboy Bebop,カウボーイビバップ,8.75,"Action, Award Winning, Sci-Fi, Adult Cast, Space","Crime is timeless. By the year 2071, humanity ...",TV,26,"Apr 3, 1998 to Apr 24, 1999",...,Sunrise,Original,24 min. per ep.,R - 17+ (violence & profanity),50,41,90976,1077271,2089081,https://cdn.myanimelist.net/images/anime/4/196...
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,カウボーイビバップ 天国の扉,8.38,"Action, Sci-Fi, Adult Cast, Space","Another day, another bounty—such is the life o...",Movie,1,"Sep 1, 2001",...,Bones,Original,1 hr. 55 min.,R - 17+ (violence & profanity),252,663,1827,234731,417292,https://cdn.myanimelist.net/images/anime/1439/...
2,6,Trigun,Trigun,トライガン,8.22,"Action, Adventure, Sci-Fi, Adult Cast, Shounen","Vash the Stampede is the man with a $$60,000,0...",TV,26,"Apr 1, 1998 to Sep 30, 1998",...,Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older,433,268,17956,405835,846067,https://cdn.myanimelist.net/images/anime/1130/...
3,7,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),7.24,"Action, Drama, Mystery, Supernatural, Detective","Though hidden away from the general public, Wi...",TV,26,"Jul 3, 2002 to Dec 25, 2002",...,Sunrise,Original,25 min. per ep.,PG-13 - Teens 13 or older,3558,2003,720,46691,132072,https://cdn.myanimelist.net/images/anime/10/19...
5,15,Eyeshield 21,UNKNOWN,アイシールド21,7.91,"Sports, Team Sports, Shounen","Shy, reserved, and small-statured, Deimon High...",TV,145,"Apr 6, 2005 to Mar 19, 2008",...,Gallop,Manga,23 min. per ep.,PG-13 - Teens 13 or older,909,1439,2145,93938,197662,https://cdn.myanimelist.net/images/anime/1079/...
6,16,Hachimitsu to Clover,Honey and Clover,ハチミツとクローバー,7.98,"Comedy, Drama, Romance, Adult Cast, Love Polyg...","Yuuta Takemoto, a sophomore at an arts college...",TV,24,"Apr 15, 2005 to Sep 27, 2005",...,J.C.Staff,Manga,23 min. per ep.,PG-13 - Teens 13 or older,787,996,4213,87408,287838,https://cdn.myanimelist.net/images/anime/1301/...
7,17,Hungry Heart: Wild Striker,UNKNOWN,ハングリーハート Wild Striker,7.57,"Sports, Team Sports, Shounen",As the younger brother of Japanese soccer star...,TV,52,"Sep 11, 2002 to Sep 10, 2003",...,Nippon Animation,Manga,23 min. per ep.,PG-13 - Teens 13 or older,1904,4982,245,14153,26981,https://cdn.myanimelist.net/images/anime/12/49...
8,18,Initial D Fourth Stage,UNKNOWN,頭文字〈イニシャル〉D FOURTH STAGE,8.18,"Action, Drama, Racing, Seinen",Takumi Fujiwara finally joins Ryousuke and Kei...,TV,24,"Apr 17, 2004 to Feb 18, 2006",...,A.C.G.T.,Manga,27 min. per ep.,PG-13 - Teens 13 or older,486,1319,1463,121609,219002,https://cdn.myanimelist.net/images/anime/9/105...
9,19,Monster,Monster,モンスター,8.90,"Drama, Mystery, Suspense, Adult Cast, Psycholo...","Dr. Kenzou Tenma, an elite neurosurgeon recent...",TV,74,"Apr 7, 2004 to Sep 28, 2005",...,Madhouse,Manga,24 min. per ep.,R+ - Mild Nudity,25,114,63774,527648,1364406,https://cdn.myanimelist.net/images/anime/10/18...
10,20,Naruto,Naruto,ナルト,8.03,"Action, Adventure, Fantasy, Martial Arts, Shounen","Twelve years ago, a colossal demon fox terrori...",TV,220,"Oct 3, 2002 to Feb 8, 2007",...,Studio Pierrot,Manga,23 min. per ep.,PG-13 - Teens 13 or older,719,9,87848,2172126,3165053,https://cdn.myanimelist.net/images/anime/1141/...
11,21,One Piece,One Piece,ONE PIECE,8.72,"Action, Adventure, Fantasy, Shounen",Barely surviving in a barrel after passing thr...,TV,UNKNOWN,"Oct 20, 1999 to ?",...,Toei Animation,Manga,24 min.,PG-13 - Teens 13 or older,61,17,256516,1560541,2732488,https://cdn.myanimelist.net/images/anime/1244/...
12,22,Tennis no Oujisama,The Prince of Tennis,テニスの王子様,7.85,"Sports, School, Shounen","At the request of his father, tennis prodigy R...",TV,178,"Oct 10, 2001 to Mar 23, 2005",...,Trans Arts,Manga,22 min. per ep.,PG-13 - Teens 13 or older,1053,1431,3083,89095,199454,https://cdn.myanimelist.net/images/anime/6/216...
14,24,School Rumble,School Rumble,スクールランブル,7.88,"Comedy, Romance, Gag Humor, Love Polygon, Scho...","Just the words ""I love you,"" and everything ch...",TV,26,"Oct 5, 2004 to Mar 29, 2005",...,Studio Comet,Manga,23 min. per ep.,PG-13 - Teens 13 or older,989,825,5436,155471,347820,https://cdn.myanimelist.net/images/anime/1465/...
15,25,Sunabouzu,Desert Punk,砂ぼうず,7.36,"Action, Adventure, Comedy, Sci-Fi, Ecchi, Seinen","The Great Kanto Desert, a sweltering wasteland...",TV,24,"Oct 6, 2004 to Mar 30, 2005",...,Gonzo,Manga,24 min. per ep.,R - 17+ (violence & profanity),2867,1776,883,58383,153817,https://cdn.myanimelist.net/images/anime/6/755...
16,26,Texhnolyze,Texhnolyze,TEXHNOLYZE,7.76,"Avant Garde, Drama, Mystery, Sci-Fi, Suspense,...","In the dark underground city of Lux, people li...",TV,22,"Apr 17, 2003 to Sep 25, 2003",...,Madhouse,Original,23 min. per ep.,R+ - Mild Nudity,1301,961,5841,65031,297629,https://cdn.myanimelist.net/images/anime/1027/...
17,27,Trinity Blood,Trinity Blood,トリニティ・ブラッド,7.28,"Action, Fantasy, Sci-Fi, Vampire","Following Armageddon, an apocalyptic war, mank...",TV,24,"Apr 29, 2005 to Oct 28, 2005",...,Gonzo,Light novel,24 min. per ep.,R - 17+ (violence & profanity),3304,1408,1449,84443,203144,https://cdn.myanimelist.net/images/anime/10/24...
18,28,Yakitate!! Japan,Yakitate!! Japan,焼きたて!! ジャぱん,7.90,"Comedy, Gourmet, Shounen","While countries such as France, England, and G...",TV,69,"Oct 12, 2004 to Mar 14, 2006",...,Sunrise,Manga,24 min. per ep.,PG-13 - Teens 13 or older,949,2359,962,43482,106085,https://cdn.myanimelist.net/images/anime/3/764...
19,29,Zipang,UNKNOWN,ジパング,7.54,"Action, Drama, Sci-Fi, Adult Cast, Historical,...",A Ripple in Time Turns the Crucial Tide of WWI...,TV,26,"Oct 8, 2004 to Apr 1, 2005",...,Studio Deen,Manga,24 min. per ep.,PG-13 - Teens 13 or older,2059,5080,212,8625,25705,https://cdn.myanimelist.net/images/anime/13/75...
20,30,Shinseiki Evangelion,Neon Genesis Evangelion,新世紀エヴァンゲリオン,8.37,"Avant Garde, Award Winning, Drama, Sci-Fi, Sus...",Fifteen years after a cataclysmic event known ...,TV,26,"Oct 4, 1995 to Mar 27, 1996",...,"Gainax, Tatsunoko Production",Original,24 min. per ep.,PG-13 - Teens 13 or older,268,43,120244,1238080,2068059,https://cdn.myanimelist.net/images/anime/1314/...
21,31,Shinseiki Evangelion Movie: Shi to Shinsei,Neon Genesis Evangelion: Death & Rebirth,新世紀エヴァンゲリオン劇場版 シト新生,7.50,"Drama, Sci-Fi, Suspense, Mecha, Psychological","In the year 2015, more than a decade has passe...",Movie,1,"Mar 15, 1997",...,"Gainax, Production I.G, Tatsunoko Production",Original,1 hr. 44 min.,R - 17+ (violence & profanity),2215,1010,818,156443,283702,https://cdn.myanimelist.net/images/anime/1993/...

In [ ]:
columnas = ["Genres", "Type","Episodes", "Status", "Studios", "Source"]

for col in columnas:
  print(f"Conteo para {col}")

  print(Animes_Bien_Valorados[col].value_counts().head())
  print("\n")

Conteo para Genres
Genres
Hentai                                                  158
Music                                                   100
Action, Adventure, Fantasy, Historical, Martial Arts     96
Action, Adventure, Fantasy, Shounen                      71
Action, Adventure, Fantasy                               44
Name: count, dtype: int64


Conteo para Type
Type
TV         2438
Movie       951
OVA         679
ONA         594
Special     321
Name: count, dtype: int64


Conteo para Episodes
Episodes
1     1734
12     936
13     431
26     252
2      251
Name: count, dtype: int64


Conteo para Status
Status
Finished Airing     5253
Currently Airing      82
Name: count, dtype: int64


Conteo para Studios
Studios
Toei Animation       256
Sunrise              250
J.C.Staff            182
TMS Entertainment    161
Madhouse             157
Name: count, dtype: int64


Conteo para Source
Source
Manga          2312
Original       1043
Light novel     562
Game            233
Web manga       230
Name: count, dtype: int64

# ¿Por qué vale la pena responder la pregunta?  
En los últimos años se ha hecho notar como el consumo de películas y series de animación japonesa se ha vuelto cada vez más masivo. De la mano de títulos taquilleros como Naruto, One Piece o Kimetsu no Yaiba, el mercado del anime, si bien es aún menor que el de la producción audiovisual tradicional, pasó de ser un nicho cultural, a masificarse con notoriedad por fuera de Japón, su país de origen. Es significativo también que artistas conocidos a nivel mundial como Bad Bunny incluyan referencias a este tipo de consumos culturales. Para considerar algunos números, (agregar notas periodísticas).

Si por sí solo el peso económico de este crecimiento acelerado no fuese suficiente, el aumento del interés en una producción asiática se enmarca también en la transformación de las relaciones de fuerzas políticas a nivel global, donde las potencias occidentales del hemisferio norte están viéndose enfrentadas al enorme crecimiento de China, y donde países cómo este, Korea, India y Japón aumentan su influencia cultural en todo el planeta. De la pandemia en adelante, el fenómeno TikTok ha jugado un rol importante como plataforma de difusión de contenido vinculado a oriente, acercandolo a un público nuevo y en un formato de fácil difusión (agregar un paper).